DROP TABLE BUISNESS CASCADE CONSTRAINTS;
DROP TABLE BUISNESS_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PHOTO CASCADE CONSTRAINTS;
DROP TABLE REVIEWS CASCADE CONSTRAINTS;
DROP TABLE USER_YELP CASCADE CONSTRAINTS;

DROP TABLE USER_FRIEND CASCADE CONSTRAINTS;
DROP TABLE USER_COMPLIMENTS_FRIENDS CASCADE CONSTRAINTS;
DROP TABLE PROVIDE_USER_REVIEWS CASCADE CONSTRAINTS;
DROP TABLE VOTES_USER_REVIEWS CASCADE CONSTRAINTS;
DROP TABLE BELONG_T0_REVIEW_BUISNESS CASCADE CONSTRAINTS;
DROP TABLE BELONG_TO_PHOTO_BUISNESS CASCADE CONSTRAINTS;
DROP TABLE HASA_BUISNESS_BSNCATG CASCADE CONSTRAINTS;
DROP TABLE MARKED CASCADE CONSTRAINTS;
