/*query5*/

Select Y.USER_ID, Y.F_NAME, count(*) as number_states
FROM (
  Select Y.USER_ID,Y.F_NAME,B.states,COUNT(*)
  FROM USER_YELP Y, REVIEWS R ,BUISNESS B 
  WHERE Y.USER_ID =R.AUTHOR_ID
  AND B.BUISNESS_ID=R.B_ID
  group by Y.USER_ID, Y.F_NAME, B.STATES
  ) group by Y.USER_ID, Y.F_NAME

HAVING COUNT(*) >5
ORDER BY number_states DESC ;

-- LIST OF USERS TRAVELLED
CREATE VIEW TRAVELERS AS
SELECT D.USER_ID, COUNT(DISTINCT b.stateS) AS STATESTRAVELLED
FROM RATES_USER_BUISNESS D, BUISNESS B
WHERE D.BUISNESS_ID = B.BUISNESS_ID
GROUP BY D.USER_ID;

-- FINAL QUERY
SELECT Y.USER_ID, Y.F_NAME, Y.L_NAME, U.STATESTRAVELLED
FROM USER_yelp Y, travelers U
WHERE U.user_ID = Y.user_ID AND U.STATESTRAVELLED >= 5
ORDER BY U.STATESTRAVELLED, CAST(SUBSTR(Y.USER_ID, 2,3) AS int) ASC;




