/*Student Name:Aastha Jain ,Student ID:014868722*/

/*QUERY8*/

Select b.BUISNESS_ID,b.BUISNESS_NAME,COUNT(*) AS NUMBER_REVIEWS
FROM BUISNESS b
INNER JOIN REVIEWS r
on b.BUISNESS_ID = r.B_ID
WHERE b.BUISNESS_ID IN(
    SELECT distinct(b.BUISNESS_ID)
    FROM BUISNESS b
    INNER JOIN REVIEWS r
    on b.BUISNESS_ID = r.B_ID
    where r.RATING=5
    and b.states LIKE '%CA%'
    )
  AND b.states LIKE '%CA%'
  GROUP BY b.BUISNESS_ID, b.BUISNESS_NAME
  HAVING COUNT(*)>10
  ORDER BY b.BUISNESS_ID ASC, NUMBER_REVIEWS DESC ;
  
  
