/*QUERY 9*/
SELECT B.BUISNESS_ID,B.BUISNESS_NAME ,COUNT(*) AS NUMBER_REVIEWS
FROM BUISNESS B
INNER JOIN REVIEWS R 
ON B.BUISNESS_ID = R.B_ID
WHERE R.RATING =5
AND R.AUTHOR_ID IN (
        SELECT Y.USER_ID
        FROM USER_YELP Y
        INNER JOIN REVIEWS R
        ON Y.USER_ID = R.AUTHOR_ID
        GROUP BY Y.USER_ID
        HAVING COUNT(*)=1
        )
GROUP BY B.BUISNESS_ID, B.BUISNESS_NAME
HAVING COUNT(*) >50
ORDER BY NUMBER_REVIEWS DESC,B.BUISNESS_NAME ASC ,B.BUISNESS_ID ASC;
        